package types;
public enum Perms {
	DEFAULT,
	CREATE_CAMP,
	DELETE_CAMP,
	EDIT_CAMP,
	VIEW_EVERY_CAMP,
	APPROVE_CAMP_SUGGESTION,
	VIEW_CAMP_ENQUIRY,
	SUBMIT_CAMP_ENQUIRY,
	REPLY_CAMP_ENQUIRY,
	SUBMIT_CAMP_SUGGESTION,
	VIEW_CAMP_SUGGESTION,
	EDIT_CAMP_SUGGESTION,
	DELETE_CAMP_SUGGESTION,
	VIEW_CAMP_STUDENT_INFORMATION,
	VIEW_AVAILABLE_CAMP,
	REGISTER_AS_ATTENDEE,
	REGISTER_AS_COMMITTEE,
	WITHDRAW_AS_ATTENDEE
}
